BrewReview/urls.py
from django.urls import path
from BrewReview import views


app_name = 'BrewReview'


urlpatterns = [
    path('', views.index, name='index'),
    path('map/', views.map, name='map'),

    path('shops/', views.shops, name='shops'),
    path('shops/<slug:shop_slug>/', views.show_shop, name='show_shop'),
    path('add_shop/', views.add_shop, name='add_shop'),
    path('remove_shop/<slug:slug>', views.remove_shop, name='remove_shop'),

    path('shops/<slug:shop_slug>/add_review/', views.add_review, name='add_review'),
    path('remove_review/<int:review_id>/', views.remove_review, name='remove_review'),

    path('searched/', views.searched, name='searched'),

    path('profile/', views.profile, name='profile'),
    path('account_settings/', views.account_settings, name='account_settings'),
    path('change_username/', views.change_username, name='change_username'),
    path('delete_account/', views.delete_account, name='delete_account'),

]

Brew_Review_Project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from BrewReview import views

from django.conf import settings
from django.conf.urls.static import static
        

urlpatterns = [
    path('', views.index, name='index'),
    path('BrewReview/', include('BrewReview.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BrewReview/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class CoffeeShop(models.Model):
    # Table for storing details about a coffee shop
    NAME_MAX_LENGTH = 128
    DESC_MAX_LENGTH = 1000
    ADDRESS_MAX_LENGTH = 256
    POSTCODE_MAX_LENGTH = 10

    owner_id = models.ForeignKey(User, on_delete=models.CASCADE)
    shop_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=DESC_MAX_LENGTH, default='')

    address_line_1 = models.CharField(max_length=ADDRESS_MAX_LENGTH, default='')
    postcode = models.CharField(max_length=POSTCODE_MAX_LENGTH, default='')
    city = models.CharField(max_length=ADDRESS_MAX_LENGTH, null = True, default='')
    country = models.CharField(max_length=ADDRESS_MAX_LENGTH, default='')

    lat = models.FloatField(default=None, null=True,)
    lng = models.FloatField(default=None, null=True)

    picture = models.ImageField(upload_to='shop_images', blank=True)
    serves_food = models.BooleanField(default=False)
    rating = models.FloatField(default=0, null=True)
    price = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(CoffeeShop, self).save(*args, **kwargs)



class Review(models.Model):
    # Table for storing details about a coffee shop review
    TITLE_MAX_LENGTH = 256
    REVIEW_MAX_LENGTH = 1000

    review_id = models.AutoField(primary_key=True)
    coffee_shop = models.ForeignKey(CoffeeShop, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    rating = models.IntegerField(default=0)
    review = models.TextField(max_length=REVIEW_MAX_LENGTH)

    def __str__(self):
        return str(self.review_id)

BrewReview/forms.py
from typing import Any
from django import forms

from BrewReview.models import CoffeeShop, Review
import googlemaps

class CoffeeShopForm(forms.ModelForm):
    gmaps = googlemaps.Client(key="AIzaSyDDv5ekhgkSI-hTpzWp8bXYwxrP0D8IBjQ")

    name = forms.CharField(max_length=128, help_text="Please enter the shop name.")
    description = forms.CharField(max_length=1000, help_text="Please enter a shop description.")
    serves_food = forms.BooleanField(help_text="Please enter if the shop serves food.", required=False)
    price = forms.ChoiceField(widget=forms.RadioSelect, choices=[(i, i) for i in range(1, 6)], help_text="Please enter how expensive the shop is on a range 1 to 5.")
    address_line_1 = forms.CharField(max_length=128, help_text="Please enter the first line of address")
    postcode = forms.CharField(max_length=10, help_text="Please enter the postcode")
    city = forms.CharField(max_length=128, help_text="Please enter the city")
    country = forms.CharField(max_length=128, help_text="Please enter the country")
    picture = forms.ImageField(required=False)

    class Meta:
        model = CoffeeShop
        fields = ('name', 'description', 'serves_food', 'price', 'address_line_1', 'postcode', 'city', 'country', 'picture')


class ReviewForm(forms.ModelForm):
    title = forms.CharField(max_length=Review.TITLE_MAX_LENGTH, help_text="Please enter the title of the review.")
    rating = forms.ChoiceField(widget=forms.RadioSelect, choices=[(i, i) for i in range(1, 6)], help_text="Please enter your rating of the shop on a range 1 to 5.")
    review = forms.CharField(max_length=Review.REVIEW_MAX_LENGTH, help_text="Please enter your review of the shop.")


    class Meta:
        model = Review
        fields = ('title', 'rating', 'review')


class ChangeUsernameForm(forms.Form):
    new_username = forms.CharField(max_length=150)

BrewReview/views.py
from django.contrib.auth.decorators import login_required

from django.db.models import Avg
from django.urls import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse


from django.shortcuts import redirect, get_object_or_404


from BrewReview.forms import CoffeeShopForm, ReviewForm, ChangeUsernameForm
from BrewReview.models import CoffeeShop, Review

import googlemaps


def index(request):
    try:
        recent_reviews = Review.objects.order_by('-date')[:6]  # Fetch the 4 most recent reviews
        for review in recent_reviews:
            shop_name = CoffeeShop.objects.get(pk=review.coffee_shop_id).name
            slug = CoffeeShop.objects.get(pk=review.coffee_shop_id).slug
            review.shop_name = shop_name
            review.shop_slug = slug
    except:
        recent_reviews = None
    return render(request, 'BrewReview/index.html', {'navbar_active':'home', 'recent_reviews': recent_reviews})


def get_recent_reviews(request):
    recent_reviews = Review.objects.order_by('-date')[:6]
    reviews_data = []
    for review in recent_reviews:
        review_data = {
            'title': review.title,
            'user': review.user.username,
            'shop_name': review.coffee_shop.name,
            'rating': review.rating,
            'shop_slug': review.coffee_shop.slug
        }
        reviews_data.append(review_data)
    return JsonResponse({'recent_reviews': reviews_data})

def map(request, center_lat=55.8724, center_lng=-4.2900, zoom=11):
    gmaps = googlemaps.Client(key="AIzaSyDDv5ekhgkSI-hTpzWp8bXYwxrP0D8IBjQ")
    filter_param = request.GET.get('filter', False)
    if filter_param == "on":
        filter_param = True
        coffee_shop_list = CoffeeShop.objects.filter(serves_food=True)
    else:
        filter_param = False
        coffee_shop_list = CoffeeShop.objects.all()
    center_lat = request.GET.get('lat',55.8724)
    center_lng = request.GET.get('lng',-4.2900)
    zoom = request.GET.get('zoom',12)
    length = len(coffee_shop_list)
    names = coffee_shop_list[0].name
    lat_list = str(coffee_shop_list[0].lat)
    lng_list = str(coffee_shop_list[0].lng)
    url_list = str(coffee_shop_list[0].slug)
    for coffee_shop in coffee_shop_list[1:]:
        names += ", " + coffee_shop.name
        lat_list += ","+str(coffee_shop.lat)
        lng_list += ","+str(coffee_shop.lng)
        url_list += ","+str(coffee_shop.slug)

    # addresses += "!"+coffee_shop.address.address_line_1+", "+coffee_shop.address.postcode+", "+coffee_shop.address.city+", "+coffee_shop.address.country
    context_dict = {'navbar_active':'map', 'length': length, 'names': names, 'lat_list': lat_list,
                    'lng_list': lng_list, 'url_list': url_list, 'center_lat':center_lat,
                    'center_lng':center_lng, 'zoom':zoom, 'shops':coffee_shop_list,
                    'filter_param':filter_param}
    return render(request, 'BrewReview/map.html', context=context_dict)

def shops(request):
    filter_param = request.GET.get('filter', False)
    if filter_param == "on":
        filter_param = True
        coffee_shop_list = CoffeeShop.objects.filter(serves_food=True)
    else:
        filter_param = False
        coffee_shop_list = CoffeeShop.objects.all()
    
    sort_by = request.GET.get('sort_by')
    if sort_by == 'rating_desc':
        coffee_shop_list = coffee_shop_list.order_by('-rating')
    elif sort_by == 'price_desc':
        coffee_shop_list = coffee_shop_list.order_by('-price')

    context_dict = {'navbar_active':'shops', 'shops':coffee_shop_list, 'filter_param':filter_param}
    return render(request, 'BrewReview/shops.html', context=context_dict)

def show_shop(request, shop_slug):
    context = {}
    try:
        shop = CoffeeShop.objects.get(slug=shop_slug)
        reviews = Review.objects.filter(coffee_shop=shop)
        context['reviews'] = reviews
        context['shop'] = shop
    except CoffeeShop.DoesNotExist:
        context['shop'] = None
        context['reviews'] = None
    return render(request, 'BrewReview/shop.html', context=context)

@login_required
def add_shop(request):
    gmaps = googlemaps.Client(key="AIzaSyDDv5ekhgkSI-hTpzWp8bXYwxrP0D8IBjQ")  # Replace "YOUR_API_KEY" with your actual API key
    form = CoffeeShopForm()
    # A HTTP POST?
    if request.method == 'POST':
        form = CoffeeShopForm(request.POST, request.FILES)  # Pass request.FILES to handle image upload
        if form.is_valid():
            shop = form.save(commit=False)  # Don't commit yet to set owner_id
            shop.owner_id = request.user  # Set the owner_id to the user submitting the form
            shop.save()
            
            address = (str(shop.address_line_1) + ", " + str(shop.postcode) + ", " +
                       str(shop.city) + ", " + str(shop.country))
            result = gmaps.geocode(address)
            if result:
                location = result[0].get("geometry", {}).get("location")
                if location:
                    shop.lat = location.get("lat")
                    shop.lng = location.get("lng")
                    shop.save()
                    return redirect('/BrewReview/')
                else:
                    print("Invalid address")
            else:
                print("Invalid address")
        else:
            print(form.errors)
    return render(request, 'BrewReview/add_shop.html', {'form': form})


@login_required
def remove_shop(request, slug):
    shop = get_object_or_404(CoffeeShop, slug=slug)
    if request.user == shop.owner_id:
        shop.delete()
        return redirect('BrewReview:profile')



@login_required
def add_review(request, shop_slug):
    try:
        shop = CoffeeShop.objects.get(slug=shop_slug)
    except CoffeeShop.DoesNotExist:
        shop = None

    if shop is None:
        return redirect('/BrewReview/')
    
    form = ReviewForm()

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.coffee_shop = shop
            review.user = request.user
            review.save()

            # Calculate the new average rating
            new_avg_rating = Review.objects.filter(coffee_shop=shop).aggregate(Avg('rating'))['rating__avg']
            if new_avg_rating is not None:
                # Update the coffee shop rating with the new average rating
                shop.rating = round(new_avg_rating, 1)  # Round to one decimal place
                shop.save()

            return redirect(reverse('BrewReview:show_shop', kwargs={'shop_slug': shop_slug}))
        else:
            print(form.errors)
    return render(request, 'BrewReview/add_review.html', {'form': form, 'shop': shop})


@login_required
def remove_review(request, review_id):
    try:
        review = Review.objects.get(review_id=review_id)
        if review.user == request.user:
            review.delete()
        return redirect('BrewReview:profile')
    except:
        return redirect('BrewReview:index')


def searched(request):
    context_dict = {'navbar':'shops'}
    if request.method == 'POST':
        search = request.POST.get('search', '')
        shops = CoffeeShop.objects.filter(name__contains=search)
        return render(request, 'BrewReview/searched.html', {'search':search, 'shops':shops, 'context':context_dict})
    else:
        return render(request, 'BrewReview/searched.html', context=context_dict)


@login_required
def account_settings(request):
    context_dict = {'navbar_active':'settings'}
    return render(request, 'BrewReview/account_settings.html', context=context_dict)


@login_required
def change_username(request):
    if request.method == 'POST':
        form = ChangeUsernameForm(request.POST)
        if form.is_valid():
            new_username = form.cleaned_data['new_username']
            request.user.username = new_username
            request.user.save()
            return redirect('BrewReview:profile')  # Redirect to user profile page
    else:
        form = ChangeUsernameForm()
    return render(request, 'BrewReview/change_username.html', {'form': form})

@login_required
def delete_account(request):
    if request.method == 'POST':
        request.user.delete()
    return redirect('BrewReview:index')

@login_required
def profile(request):
    shops = []
    user_id = request.user.id
    try:
        user_reviews = Review.objects.filter(user=user_id)
        recent_reviews=user_reviews.order_by('-date')
        for review in recent_reviews:
            shop_name = CoffeeShop.objects.get(pk=review.coffee_shop_id).name
            slug = CoffeeShop.objects.get(pk=review.coffee_shop_id).slug
            review.shop_name = shop_name
            review.shop_slug = slug 
            shop_info = {
                'name': review.coffee_shop.name,
                'slug': review.coffee_shop.slug,
                'rating': review.coffee_shop.rating
            }
            shops.append(shop_info)
    except:
        shops = None
        recent_reviews = None
    try:
        owned_shops = CoffeeShop.objects.filter(owner_id=user_id)
    except:
        owned_shops = None
    return render(request, 'BrewReview/profile.html', context = {'navbar_active':'profile', 'recent_reviews': recent_reviews, 'shops':shops, 'owned_shops':owned_shops})

templates/BrewReview/account_settings.html
{% extends 'BrewReview/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Account Settings
{% endblock %}

{% block heading_block %}
<div class="jumbotron p-4 text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ user.username }}'s Settings</h1>
    </div>
</div>
{% endblock %}

{% block body_block %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="custom-container">
                <h1 class="display-4">Change your Settings</h1>
                <p class="lead">On this page you can alter some of the details associated with your account using the buttons below.<br>
                You can change your username or password, and also delete your account should you choose to.</p>
                <div class="btn-container">
                    <a href="{% url 'BrewReview:change_username' %}" class="btn btn-primary"><h3>Change your Username</h3></a>
                    <a href="{% url 'auth_password_change' %}" class="btn btn-primary"><h3>Change your Password</h3></a>
                    <a href="#" class="btn btn-primary btn-delete" id="delete-account-btn"><h3>Delete your Account</h3></a>
                </div>
                <p class="lead">If you delete your account, all of your reviews and any of your owned coffee shops will also be removed. <br>
                    You can create an account again at any time, we hope to see you soon!</p>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="deleteAccountModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Account Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                    Are you sure you want to delte your account?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <form action="{% url 'BrewReview:delete_account' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Confirm Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% block password_changed_block %}
{% endblock %}
{% endblock %}

templates/BrewReview/add_shop.html
{% extends 'BrewReview/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add Shop
{% endblock %}

{% block heading_block %}
<div class="jumbotron p-4 text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Add your Coffee Shop</h1>
    </div>
</div>
{% endblock %}

{% block body_block %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="custom-container">
                <h1 class="display-4">Add Your Shop</h1>
                <p class="lead">On this page you can add your own coffee shop to the site.<br>
                    We will need the following information in order to create a page for your shop as well as show it on
                    the map.</p>
                <form id="add_shop_form" method="post" action="{% url 'BrewReview:add_shop' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Name:</label>
                        <input type="text" class="form-control{% if form.name.errors %} is-invalid{% endif %}"
                            id="id_name" name="name" placeholder="Enter the shop name" required>
                        {% for error in form.name.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="id_description">Description:</label>
                        <textarea class="form-control{% if form.description.errors %} is-invalid{% endif %}"
                            id="id_description" name="description" rows="3" placeholder="Enter a shop description"
                            required></textarea>
                        {% for error in form.description.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="id_serves_food">Serves Food:</label>
                        <div class="custom-control custom-switch">
                            <input type="checkbox" class="custom-control-input" id="id_serves_food" name="serves_food">
                            <label class="custom-control-label" for="id_serves_food">Yes</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Select how expensive your shop is (1 = cheap, 5 = very expensive):</label>
                        <div class="form-row">
                            {% for choice in form.price %}
                            <div class="form-check form-check-inline">
                                {{ choice }}
                            </div>
                            {% endfor %}
                        </div>
                        {% for error in form.price.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    
                    <div class="form-group">
                        <label for="id_address_line_1">Address Line 1:</label>
                        <input type="text" class="form-control{% if form.address_line_1.errors %} is-invalid{% endif %}"
                            id="id_address_line_1" name="address_line_1" placeholder="Enter the first line of address"
                            required>
                        {% for error in form.address_line_1.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="id_postcode">Postcode:</label>
                        <input type="text" class="form-control{% if form.postcode.errors %} is-invalid{% endif %}"
                            id="id_postcode" name="postcode" placeholder="Enter the postcode" required>
                        {% for error in form.postcode.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="id_city">City:</label>
                        <input type="text" class="form-control{% if form.city.errors %} is-invalid{% endif %}"
                            id="id_city" name="city" placeholder="Enter the city" required>
                        {% for error in form.city.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="id_country">Country:</label>
                        <input type="text" class="form-control{% if form.country.errors %} is-invalid{% endif %}"
                            id="id_country" name="country" placeholder="Enter the country" required>
                        {% for error in form.country.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="form-group">
                        <label for="id_picture">Picture:</label>
                        <input type="file" class="form-control-file{% if form.picture.errors %} is-invalid{% endif %}" id="id_picture" name="picture">
                        {% for error in form.picture.errors %}
                        <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>                    
                    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit">Add Shop</button>
                </form>
            </div>
        </div>
    </div>
</div
{% endblock %}

templates/BrewReview/change_username.html
{% extends 'BrewReview/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Change Username
{% endblock %}

{% block heading_block %}
<div class="jumbotron p-4 text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Change Your Username</h1>
    </div>
</div>
{% endblock %}

{% block body_block %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <!-- Form Section -->
        <div class="col-md-4">
            <div class="custom-container">
                <h1 class="display-4">Change Username</h1>
                <p class="lead">On this page, you can change your username by entering a new one in the form below.</p>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_new_username">New Username:</label>
                        <input type="text" name="new_username" id="id_new_username" class="form-control{% if form.new_username.errors %} is-invalid{% endif %}" placeholder="Current username: {{ user.username }}" required autofocus>
                        {% for error in form.new_username.errors %}
                            <div class="invalid-feedback">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Change Username</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/BrewReview/profile.html
{% extends 'BrewReview/base.html' %}
{% load staticfiles %}

{% block title_block %}
Profile
{% endblock %}

{% block heading_block %}
<div class="jumbotron p-4 text-center">
    <div class="container">
        <h1 class="jumbotron-heading">{{ user.username }}'s Profile</h1>
    </div>
</div>
{% endblock %}

{% block body_block %}

<div class="container-fluid p-3">
    <a class="btn btn-outline-dark mt-auto mb-3" href="{% url 'BrewReview:account_settings' %}">User Settings</a>
    <br>
    <a class="btn btn-outline-dark mt-auto" href="{% url 'BrewReview:add_shop' %}">Add your Coffee Shop</a>
</div>


<div class="container-fluid pb-3">
    <div class="row">
        <div class="col-md-6">
            <div class="custom-container_2 h-100">
                <h1 class="display-2">Your Reviews</h1>
                <div class="row">
                    {% for review in recent_reviews %}
                    <div class="col-md-6 mb-3">
                        <div class="card h-100">
                            <div class="card-body">
                                <h5 class="card-title">{{ review.title }} by {{ review.user }}</h5>
                                <p class="card-text">Shop: {{ review.shop_name }}</p>
                                <p class="card-text">Rating: {{ review.rating }}</p>
                            </div>
                            <div class="card-footer">
                                <a href="{% url 'BrewReview:show_shop' review.shop_slug %}"
                                    class="btn btn-primary">View {{ review.shop_name }}</a>
                                <a href="{% url 'BrewReview:remove_review' review.review_id %}" class="btn btn-danger">Remove Review</a>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:2 and not forloop.last %}
                </div>
                <div class="row">
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12 mb-4">
                    <div class="custom-container_2 h-100">
                        <h1 class="display-2">Recently Visited</h1>
                        <div class="row">
                            {% for shop in shops %}
                            <div class="col-md-4 mb-5">
                                <div class="card h-100">
                                    {% if shop.picture %}
                                        <img src="{{ shop.picture.url }}" class="img-fluid" alt="{{ shop.name }}">
                                    {% else %}
                                        <img src="https://icons.iconarchive.com/icons/iconarchive/fat-sugar-food/256/Drink-Coffee-icon.png" class="img-fluid" alt="{{ shop.name }}">
                                    {% endif %}
                                    <div class="card-body p4">
                                        <div class="text-center">
                                            <h5 class="fw-bolder">{{ shop.name }}</h5>
                                            {{ shop.rating }}/5
                                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                                <div class="text-center">
                                                    <a class="btn btn-outline-dark mt-auto"
                                                        href="{% url 'BrewReview:show_shop' shop.slug %}">View
                                                        Shop</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% if forloop.counter|divisibleby:3 and not forloop.last %}
                                </div>
                                <div class="row">
                                    {% endif %}
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="custom-container_2 h-100">
                        <h1 class="display-2">Owned Shops</h1>
                        <div class="row">
                            {% for shop in owned_shops %}
                            <div class="col-md-4 mb-5">
                                <div class="card h-100">
                                    {% if shop.picture %}
                                        <img src="{{ shop.picture.url }}" class="img-fluid" alt="{{ shop.name }}">
                                    {% else %}
                                        <img src="https://icons.iconarchive.com/icons/iconarchive/fat-sugar-food/256/Drink-Coffee-icon.png" class="img-fluid" alt="{{ shop.name }}">
                                    {% endif %}
                                    <div class="card-body p4">
                                        <div class="text-center">
                                            <h5 class="fw-bolder">{{ shop.name }}</h5>
                                            {{ shop.rating }}/5
                                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                                <div class="text-center">
                                                    <a class="btn btn-outline-dark mt-auto"
                                                        href="{% url 'BrewReview:show_shop' shop.slug %}">View
                                                        Shop</a>
                                                    <a href="{% url 'BrewReview:remove_shop' shop.slug %}" class="btn btn-danger">Remove Shop</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% if forloop.counter|divisibleby:3 and not forloop.last %}
                                </div>
                                <div class="row">
                                    {% endif %}
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}